### PR TITLE
Improvements of react-native externs.

### PR DESCRIPTION
**Pull request by kiroukou**
The following pull-request incluses mainly : 
 - removal of the Quick Enums dependency.  We now are real abstract enums, no dependencies.   That improves the completion server in the same time.

 - Updated externs with some news fields

 - Addition of "android" and "ios" conditional variables to better typesafety.

Would also make react-next repo the default one, since react isn't very active at the moment (or could be specify both?)

### CODE REVIEW

**Comment by kevinresol** [comment]
This particular `NativeEvent` is only relevant to `PanResponder` and I don't think it should deserve a individual module

**Comment by kiroukou** [comment]
I'd agree but if I remember well, I decided to split it at a time to get a better completion or "go to file definition" feature support in the IDE.

If that's blocking for you, I'll change that.

**Comment by kevinresol** [comment]
Or rename it to something like `PanResponderNativeEvent`?

**Comment by kevinresol** [comment]
I mostly use this library with coconut, which depends on react-next as well. So I think I like the idea of using react-next.

**Comment by kiroukou** [comment]
> Or rename it to something like `PanResponderNativeEvent`?

Even better ;)

And good news concerning react-next !

Would you like me to correct the PR ?

**Comment by kevinresol** [comment]
Looks good to me. For smaller stuff I think you can commit directly

**Comment by kiroukou** [comment]
Ok perfect.

**Pull request merged**
